### ISSUE TITLE
Error when saving shipping document

### ISSUE THREAD

**Issue by xqliu** [betterlife/psi#271]
Reproduce: saving a shipping document in UI.
Expect: Error pops up and tells the user it's not allowed to change shipping directly.
Actual: Error occurred and exception attached as below

> Written by @xqliu
> Created at 2015-08-14T10:05:18.000+0800
> Link to http://betterlife.atlassian.net/browse/BE-138

**Comment by xqliu** [comment]
bq. [2015-07-13 23:34:44 +0800] [51459] [ERROR] Error handling request
Traceback (most recent call last):
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask_admin/base.py", line 359, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask_admin/model/base.py", line 1633, in edit_view
    if self.update_model(form, model):
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask_admin/contrib/sqla/view.py", line 1010, in update_model
    if not self.handle_view_exception(ex):
  File "/Users/larry/Projects/betterlife/Flask_ERP/views/base.py", line 37, in handle_view_exception
    return super(ModelView, self).handle_view_exception(exc)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask_admin/contrib/sqla/view.py", line 1006, in update_model
    form.populate_obj(model)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/wtforms/form.py", line 96, in populate_obj
    field.populate_obj(obj, name)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask_admin/contrib/sqla/fields.py", line 248, in populate_obj
    field.populate_obj(model, None)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/flask_admin/model/fields.py", line 126, in populate_obj
    field.populate_obj(obj, name)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/wtforms/fields/core.py", line 323, in populate_obj
    setattr(obj, name, self.data)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 802, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 824, in fire_replace_event
    self._replace_token or self._init_append_or_replace_token())
  File "/Users/larry/Projects/betterlife/Flask_ERP/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 85, in set_
    newvalue_state = attributes.instance_state(newvalue)
AttributeError: 'unicode' object has no attribute '_sa_instance_state'

> Written by @xqliu
> Created at 2015-08-14T10:05:49.881+0800
